### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by jinzihao** [theotterlord/deckmaster#25]
Hi Reuben, I find many data fields in DeckMaster are rendered as HTML (like the "combos" field in the screenshot). I believe this is an XSS vulnerability, enabling a malicious ycb file to execute scripts inside DeckMaster. Maybe consider using innerText / textContent to replace innerHTML somewhere in your code?

(I'm working on a project to investigate the security of Electron apps. I see this is a personal project and may not affect too many users, but anyway I'm obliged to report every vulnerability. Hopefully this doesn't bother you...)

![image](https://user-images.githubusercontent.com/4397423/156114335-f798e2eb-9b0b-4435-b1e7-3e11e4d36089.png)
![image](https://user-images.githubusercontent.com/4397423/156114700-4868959b-661b-4ec6-8f2c-5841cdae9c79.png)

**Comment by TheOtterlord** [comment]
Hi jinzihao! Thanks for letting me know. Yeah, the content provided to these fields will normally be by the user, but as users can share their files with others, it does have a small, but existing attack surface.

I've not had time to work on this project for a while, but I would like to get back to it at some point (hence why it's not archived). Luckily in this case, I don't think my project has many (if any) active users, but I will fix this just in case. 

It really doesn't matter for this project, but for other project it might be a good idea to contact the maintainer(s) via a contact email or via something detailed in the security policy. It obviously can't be done here as I don't have any contact details (I'll fix that soon), but most projects will have something, even if it's just an official Discord server.
